title: Geoffrey Pereira
logo: /assets/img/GP-CL-RD.png
#description: text below image
show_download: false
#theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
- jekyll-remote-theme

